name: callbundle
description: "Native incoming & outgoing call UI for Flutter. Provides CallKit on iOS and TelecomManager + adaptive notifications on Android."
version: 1.0.13
homepage: https://ikolvi.com
repository: https://github.com/Ikolvi/callbundle
issue_tracker: https://github.com/Ikolvi/callbundle/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  callbundle_platform_interface: ^1.0.0
  callbundle_android: ^1.0.0
  callbundle_ios: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: callbundle_android
      ios:
        default_package: callbundle_ios
