name: callbundle
description: "Native incoming & outgoing call UI for Flutter. Provides CallKit on iOS and TelecomManager + adaptive notifications on Android."
version: 1.0.0
homepage: https://ikolvi.com
repository: https://github.com/Ikolvi/callbundle
issue_tracker: https://github.com/Ikolvi/callbundle/issues
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  callbundle_platform_interface:
    path: ../callbundle_platform_interface
  callbundle_android:
    path: ../callbundle_android
  callbundle_ios:
    path: ../callbundle_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: callbundle_android
      ios:
        default_package: callbundle_ios
