name: callbundle_android
description: "Android implementation of the CallBundle federated Flutter plugin. Provides ConnectionService + TelecomManager + OEM-adaptive notifications."
version: 1.0.6
homepage: https://ikolvi.com
repository: https://github.com/Ikolvi/callbundle/tree/main/callbundle_android
issue_tracker: https://github.com/Ikolvi/callbundle/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  callbundle_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: callbundle
    platforms:
      android:
        package: com.callbundle.callbundle_android
        pluginClass: CallBundlePlugin
